name: Variable Scope Demo

# Workflow-level variables
env:
  MY_WORKFLOW_VARIABLE: "This is a workflow-level variable"

on:
  push:
    branches:
      - main

jobs:
  show-variables:
    runs-on: ubuntu-latest

    # Job-level variables
    env:
      MY_JOB_VARIABLE: "This is a job-level variable"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Workflow and Job Variables
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"

      - name: Step with Step-Level Variable
        # Step-level variables
        env:
          MY_STEP_VARIABLE: "This is a step-level variable"
        run: |
          echo "Workflow-level: $MY_WORKFLOW_VARIABLE"
          echo "Job-level: $MY_JOB_VARIABLE"
          echo "Step-level: $MY_STEP_VARIABLE"
